name: Sync Playlists
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y lame ffmpeg
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install yt-dlp
        uses: AnimMouse/setup-yt-dlp@v1
      - run: |
          python download.py
          python upload.py
      - uses: EndBug/add-and-commit@v9
        with:
          add: "playlists.json"
          default_author: github_actions
          message: "Ran worklow and updated playlists.json"
          push: true
